# Generated by Django 5.2.8 on 2025-11-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path_with_namespace', models.CharField(max_length=255)),
                ('web_url', models.URLField()),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path_with_namespace'],
            },
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_iid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('web_url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests', to='api.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('project', 'mr_iid')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('merge', 'Merge'), ('needs_fixes', 'Needs Fixes'), ('reject', 'Reject'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('summary_text', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_review', to='api.mergerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('suggested_fix', models.TextField(blank=True)),
                ('rule', models.CharField(blank=True, max_length=100)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.review')),
            ],
            options={
                'ordering': ['-severity', 'file_path', 'line_number'],
            },
        ),
    ]
